# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShoppingHistory', '0002_item_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='changeLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_stamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
